### ISSUE TITLE
CORS Policy problems, videos doesn't work anymore

### ISSUE THREAD

**Issue by Jarvil** [h5p/h5p-moodle-plugin#230]
Hello,

There seems to be a bug in Course Presentation (1.20.2) that embedded mp4-file links from 3rd party sites/software like dreambroker.com / Ubicast-service gives an error "video format not supported" when in Course Presentation (1.19.3) they work fine.

Suddenly all linked videos aren't working at all.

Tested on Moodle 3.3&3.5 mod_hvp 1.12 and Course Presentation (1.19.3) and Course Presentation (1.20.2)

Here is an example video from our Ubicast-service that you can test with;

https://mediamaisteri.kurssi.tv/downloads/file/v12560ed228b20nlta32/?url=https%3A//mediamaisteri.kurssi.tv/resources/vile-koiviola-mediamaisteri_8b5b/vile-koiviola-mediamaisteri_low.mp4

Error message;

"Access to video at 'https://mediamaisteri.kurssi.tv/downloads/file/v12560ed228b20nlta32/?url=https%3A//mediamaisteri.kurssi.tv/resources/vile-koiviola-mediamaisteri_8b5b/vile-koiviola-mediamaisteri_low.mp4' from origin 'http://ffffffff' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed."

@thomasmars 

![video1](https://user-images.githubusercontent.com/15193418/48545235-1ea77c80-e8ce-11e8-9029-51807255342b.PNG)

![video2](https://user-images.githubusercontent.com/15193418/48545331-57475600-e8ce-11e8-9bb5-26c9cff01dd8.PNG)

**Comment by Jarvil** [comment]
@otacke @fnoks

**Comment by thomasmars** [comment]
The problem is site configuration of mediamaisteri.kurssi.tv when using the link: https://mediamaisteri.kurssi.tv/downloads/file/v12560ed228b20nlta32/?url=https%3A//mediamaisteri.kurssi.tv/resources/vile-koiviola-mediamaisteri_8b5b/vile-koiviola-mediamaisteri_low.mp4

It sends the following response headers:
`
access-control-allow-headers: Content-Range
access-control-allow-methods: POST, GET, OPTIONS, PUT, DELETE
access-control-allow-origin: *, *
content-language: en
content-length: 0
content-type: text/html; charset=utf-8
date: Thu, 15 Nov 2018 10:18:59 GMT
location: https://mediamaisteri.kurssi.tv/resources/vile-koiviola-mediamaisteri_8b5b/vile-koiviola-mediamaisteri_low.mp4?st=yrn0SyyzkQO5ySwQYyahWw&e=1542291539&usage=download
server: nginx
status: 302
vary: Accept-Language, Cookie
x-content-type-options: nosniff, nosniff
`

Note the "access-control-allow-origin": "*, *".  It is not a valid value for the access-control-allow-origin header, which is why this fails. I would look into the server settings for mediamaisteri.kurssi.tv or tell the server administrator of that site of the problem if it is not your own site.

The reason this fails now, and not before is that interactive video sets crossorigin="anonymous" in the newest version, so that there will be no exchange of user credentials via cookies. (ref: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes). This however also means that CORS is used, and then the access-control-allow-origin header that the video service returns must be valid.

Note that if you use the following link:
https://mediamaisteri.kurssi.tv/resources/vile-koiviola-mediamaisteri_8b5b/vile-koiviola-mediamaisteri_low.mp4?st=iJdINenvvGaoAvRM5CgCnw&e=1542292247&usage=download
there are no problems because it returns the following headers:
`
access-control-allow-origin: *
Content-Length: 575618830
Content-Range: bytes 0-575618829/575618830
content-type: video/mp4
date: Thu, 15 Nov 2018 10:31:43 GMT
etag: "594d03e4-224f3f0e"
last-modified: Fri, 23 Jun 2017 12:04:52 GMT
server: nginx
status: 206
x-content-type-options: nosniff, nosniff
`
where the access-control-allow-origin header is valid.

**Comment by Jarvil** [comment]
Hello,

Thanks for the information. As we now have plenty of videos that doesn't work at all how can we disable CORS-requirement all together?

**Comment by Jarvil** [comment]
Hello,

Also where was this scope of a change announced so everyone had plenty of time beforehand to prepare their videos for this? I must have missed it myself. @thomasmars

**Comment by Jarvil** [comment]
As we now have plenty of videos that doesn't work at all how can we disable CORS-requirement all together? or can we add the header on the Moodle side server? @thomasmars @fnoks

**Comment by icc** [comment]
I believe this is related to cookie sending and privacy. 
It seems your server is sending an invalid `access-control-allow-origin` header. 
If you change this header from `*, *` to `*` everything should work fine.

**Comment by Jarvil** [comment]
Thanks,

Do you have any suggestions for a case that header is missing alltogether and for a case that the 3rd party isn't willing to add it? Could we remove this check from the H5P code and if so from where?

**Comment by icc** [comment]
If [this function](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L2033) returns `null` or `false` I believe that should drop the check, i.e. it's just about not setting the [$CFG->mod_hvp_crossorigin](https://github.com/h5p/h5p-moodle-plugin/blob/01821f0263f8c8dc55b9881c7d51c164b70994ad/locallib.php#L76
) option for moodle.

**Comment by anieminen** [comment]
Hi,

I can see that the issue is closed, but I tried changing that `H5P.getCrossOrigin()` function return value. It seems that `crossorigin` attribute is always added to the `video` tag, no matter what the function returns. I tried returning `null`, `false`, `undefined` or no value at all.

I think it should be possible to remove the attribute somehow to drop the CORS header check. We cannot be sure that all third-party video services return the correct access-control-allow-origin header.

**Comment by thomasmars** [comment]
It seems like Video defaults to use `crossorigin: 'anonymous'`, instead of not using the crossorigin attribute: https://github.com/h5p/h5p-video/commit/f2637b635324c1478746128a25b2f7aa2ea212ca
If the `$CFG->mod_hvp_crossorigin` option is not set, you would probably expect the crossorigin attribute to not be used.
@fnoks Do you recall if there was a specific reason for this change ?

**Comment by Jarvil** [comment]
Hello,

It seems that these videos without the header works with Internet Explorer 11 so it seems the browser doesn't "respect" this at all.

**Comment by Jarvil** [comment]
Hello @fnoks ,

Can you tell me does the CORS-check come with certain mod_hvp version? Or does it come when I update a specific library/libraries? I need to know this so I would know what libraries I can update "safely" without braking already existing videos.

**Comment by anieminen** [comment]
Hi,

Do you have any other tips how to bypass the `access-control-allow-origin` header check? We have a third-party video service that is not returning the header at all. They told us that they are planning to add the header "some time next year".

**Comment by Jarvil** [comment]
@icc So if I update existing _course presentation_-libraries/instances in Moodle from:

https://moodleaddress.com/mod/hvp/library_list.php

or some other existing library f.ex. _interactive video_ -library that uses the video-library the video-library is updated also in the same process?

If so can I have accurate list of which libraries video-library is connected so I can know what should I avoid updating?

**Comment by anieminen** [comment]
Also h5p.org seems to be missing the `Access-Control-Allow-Origin` header. I tried uploading the example content from https://h5p.org/interactive-video to Moodle, but the video doesn't work for the same reason.

**Comment by sr258** [comment]
For future reference: To disable the CORS-check you have to comment out or remove [lines 74-77 in h5p-video/html5.js](https://github.com/h5p/h5p-video/blob/d7f121ae63bbea8ba71e39aacc4782ea2f4e9d9e/scripts/html5.js#L74). Unfortunately this means patching the library on the server.

Would the core team accept a pull request that disables the cors check if $CFG->mod_hvp_crossorigin is set to something like 'no-check'?

**Comment by Jarvil** [comment]
We are also still waiting fix for this.

**Comment by sr258** [comment]
I've implemented a fix for this and submitted two pull requests for separate libraries (which must both be accepted for it to work):

**Comment by Jarvil** [comment]
Hello,

ping @thomasmars @icc

**Comment by thomasmars** [comment]
See https://h5ptechnology.atlassian.net/browse/HFP-2687 to follow along progress on this.

**Comment by Jarvil** [comment]
Hello,

I don't see any progress on

https://h5ptechnology.atlassian.net/browse/HFP-2687

@thomasmars

**Comment by thomasmars** [comment]
@Jarvil 
https://github.com/h5p/h5p-moodle-plugin/pull/245 has been merged in to master.
We have not been able to prioritize this yet, I'll try to push it through for the next release of the plugins.

**Comment by sr258** [comment]
You also have to merge https://github.com/h5p/h5p-video/pull/23 to fix this.

**Comment by thomasmars** [comment]
yes, it is referenced in https://h5ptechnology.atlassian.net/browse/HFP-2687

**Comment by philpav** [comment]
Videos also stopped working here since an update. 
I am not sure whether then mentioned fix will the issue for us because additionally to the CORS issue our videos are also protected by .htaccess basic authentication. 
It used to work but since a previous update the authentication dialog isn't appearing and the consoles states an `401 (Authorization Required)` error. 

Here is a sample video: 
https://h5p.org/node/569446

**Comment by thomasmars** [comment]
This should be addressed in the latest version of the plugin, please re-open if you're continuing to see problems with this.

**Comment by philpav** [comment]
Thank you @thomasmars !
The issue seems to be fixed for most browsers but it's still present in Safari on Mac OS X :(

https://h5p.org/node/569446

I'm getting "Video format not supported" because the authentication dialogue does not appear. In the console it states the same error as before the fix in the other browsers: 

`Failed to load resource: the server responded with a status of 401 (Authorization Required)
`
Also

`Blocked .../sample.mp4 from asking for credentials because it is a cross-origin request.
`

Could you please look into it. 
Thank you!

**Comment by icc** [comment]
@philpav Are the files on a different domain?
I believe 3rd-party cookies are blocked by default in Safari.

**Comment by philpav** [comment]
Yes, but Access-Control-Allow-Origin is set to "*" on the server.

**Comment by icc** [comment]
Is there a separate access cookie set for that domain? It appears as if the cookie might not have been set for the correct domain. 
Note that any cookies set by the video source server will not be set unless the client visits a page on that server if the blocking of third-party cookies is enabled.

Or may it be that you are wanting to set the `.crossOrigin` attribute to `use-credentials` ? (Though, then it shouldn't be working in any of the other browsers either...)

**Comment by philpav** [comment]
I am sorry, I don't know how to check if there is an access cookie set. 
The video is on a web server and via .htaccess I can set the access control. 

I've tried various headers and this what I have currently: 

`Header set X-Content-Type-Options "nosniff"
`
`Header set X-XSS-Protection "1; mode=block"
`
`Header always set Access-Control-Max-Age 1728000
`
`Header always set Access-Control-Allow-Origin "*"
`
`Header always set Access-Control-Allow-Methods "GET,POST,OPTIONS,DELETE,PUT"
`
`Header always set Access-Control-Allow-Headers "Content-Type,Content-Length,Authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Origin,Accept-Language"
`
`Header always set Access-Control-Allow-Credentials "true"`

But I am afraid that Safari (Webkit) now completely disallows cross-origin subresources from asking for credentials: 
https://trac.webkit.org/changeset/228486/webkit/

Someone suggested a solution here though: 
https://stackoverflow.com/questions/55131037/safari-blocks-url-from-asking-for-credentials-because-its-a-cross-origin-reques

But I don't know if this works.

**Comment by icc** [comment]
Do you have to login to see the video or can anyone view it? 
If you have to login I think this is some sort of cookie issue, so you could try adding the `crossorigin="use-credentials"` attribute to the video element just to see if it solves the issue.

By default, you no longer have to set any of the access-control headers, if you are running the latest version of Video/Interactive Video.
Have you set any H5P options in your config.php?

**Comment by philpav** [comment]
Yes, a login is necessary. 
You can check yourself here:
https://h5p.org/node/569446

Unfortunately I don't know where I shall put the mentioned attribute if I'm using the H5P editor. 
I don't have access to admin interface or the file system. So I can't tell what options were made to config.php.

**Comment by icc** [comment]
Oh, if you use videos from a site that requires a login you will either need to have your users go there first and login or you need to set your system up to use some sort of single-sign-on solution. Now you are relying on the browser to sign the user in, which will not work if that is disabled in the browser, which it is by default in Safari.
Note that this is probably a solution you would like to set up and test on the system where you will be hosting your H5P content. Note that H5P.org is only for testing the tool.

**Comment by philpav** [comment]
Thank you for your help!
I am afraid it's not possible to support Safari with this configuration. 

Even when I try to manually add `crossorigin="use-credentials"` it doesn't work in Safari. 

```
<video controls>
  <source src=".../CORS/sample.mp4" type="video/mp4" crossorigin="use-credentials"/>
</video>
```

I'm always getting 

> Blocked .../CORS/sample.mp4 from asking for credentials because it is a cross-origin request.
